
import 'core-js/modules/es.promise'
import 'core-js/modules/es.symbol'
import 'core-js/modules/es.array.iterator'
import 'core-js/modules/es.array.from'
import 'core-js/modules/es.array.find'
import 'core-js/modules/es.array.find-index'
import 'core-js/modules/es.object.assign'
import 'core-js/modules/es.object.values'
import 'core-js/modules/es.object.entries'
import 'core-js/modules/es.array.includes'
import 'core-js/modules/es.string.pad-start'
import 'babel-regenerator-runtime'
